openapi: "3.0.0"
info:
  title: Contact and Messaging API
  version: "1.0"
  description: API to work with yaslanding.com.
security:
  - BearerAuth: []
tags:
  - name: Messages


paths:
  /Messages/createMessage:
    post:
      tags:
        - Messages
      summary: Create a new user message
      security:
        - BearerAuth: []
      description: Endpoint to create a new message with user verification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        "201":
          description: Message created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMessageResponse'
        "400":
          description: Bad request - User name in form is different than records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Server error - An error occurred while creating the contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /Messages/createAnonymousMessage:
    post:
      tags:
        - Messages
      summary: Creates Message when User is not signed in
      security:
        - BearerAuth: []
      description: This endpoint is accessible after reCAPTCHA score higher than 0.5
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        "201":
          description: Message created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMessageResponse'
        "400":
          description: Bad request - User name in form is different than records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Server error - An error occurred while creating the contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /Messages/getNewMesages:
    get:
      tags:
        - Messages
      summary: Get all new unread messages
      security:
        - BearerAuth: []
      description: Endpoint for admin to retrieve all new messages.
      responses:
        "200":
          description: List of new messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNewMessagesResponse'
        "404":
          description: No unread messages found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNoSuccess'
        "403":
          description: Forrbiden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNoSuccess'
        "500":
          description: Server error - An error occurred while retrieving messages.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNoSuccess'

  /Messages/getMessage/{id}:
    get:
      tags:
        - Messages
      summary: Get a specific message by ID
      security:
        - BearerAuth: []
      description: Endpoint to retrieve a specific message by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDetails'
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Unauthorized to view this contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Server error - An error occurred while retrieving the contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /Messages/createAdminMessage:
    post:
      tags:
        - Messages
      summary: Create admins response to a users message
      description: Endpoint to retrieve a specific message by ID.
      security:
        - BearerAuth: []

      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDetails'
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Unauthorized to view this contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Server error - An error occurred while retrieving the contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /Messages/getMesagesByUser:
    get:
      tags:
        - Messages
      summary: Gets the messagingThread of signedIn user
      description: Is in use to display the sent/received messages on contact me page.
      security:
        - BearerAuth: []
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getMessageByUserResponse'
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageByUserError'
        "403":
          description: Unauthorized to view this contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageByUserError'
        "500":
          description: Server error - An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageByUserError'


