openapi: "3.0.0"
info:
  title: Contact and Messaging API
  version: "1.0"
  description: API for handling the posts.
security:
  - BearerAuth: []
tags:
  - name: Posts


paths:
  /posts/createPost:
    post:
      tags:
        - Posts
      summary: Create a new Post
      security:
        - BearerAuth: []
      description: Endpoint to create a new Post with user verification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        "201":
          description: Message created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        "400":
          description: Bad request - User name in form is different than records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErr'
        "500":
          description: Server error - An error occurred while creating the contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErrMessage'
  /posts/getPosts:
    get:
      tags:
        - Posts
      summary: Get All Posts
      security:
        - BearerAuth: []
      description: Endpoint to get all of the posts with user verification.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPostsResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErr'
        "500":
          description: Server error - An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErrMessage'
  /posts/getPost/{id}:
    get:
      tags:
        - Posts
      summary: Get A Post
      security:
        - BearerAuth: []
      description: Endpoint to get a single Post with user verification.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPostsResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErr'
        "500":
          description: Server error - An error occurred while.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErrMessage'
  /posts/editPost:
    put:
      tags:
        - Posts
      summary: Edit a Post
      security:
        - BearerAuth: []
      description: Endpoint to Edit a Post with user verification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editPostRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editPostResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErr'
        "500":
          description: Server error - An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErrMessage'
  /posts/deletePost/{id}:
    delete:
      tags:
        - Posts
      summary: Delete a Post
      security:
        - BearerAuth: []
      description: Endpoint to delete a Post with user verification.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletePostResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErr'
        "500":
          description: Server error - An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostErrMessage'