openapi: "3.0.0"
info:
  title: Contact and Messaging API
  version: "1.0"
  description: API to work with yaslanding.com.
security:
  - BearerAuth: []
tags:
  - name: Users

paths:
  /client/getUserById/{id}:
    get:
      tags:
        - Users
      summary: Get the current user object
      security:
        - BearerAuth: []
      description: Endpoint to retrieve a the full user data by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userByIdResponse'
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userByIdError'
        "403":
          description: Unauthorized to view this contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userByIdError'
        "500":
          description: Server error - An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userByIdError'